name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync

    - name: Install development dependencies
      run: |
        uv sync --extra dev

    - name: Run Flake8
      run: uv run flake8 media_gen/

    - name: Run isort
      run: uv run isort --check-only .
    
    - name: Run Black
      run: uv run black --check .
    
    # Set fake environment variables for openai
    - name: Set environment variables
      run: |
        echo "OPENAI_API_KEY=fake-api-key" >> $GITHUB_ENV
        echo "VECTOR_DB_HOST=fake-host" >> $GITHUB_ENV
        echo "VECTOR_DB_PORT=fake-port" >> $GITHUB_ENV
        echo "TAVILY_API_KEY=fake-api-key" >> $GITHUB_ENV

    - name: Run Pytest
      run: uv run pytest -vv --cov=media_gen --cov-config=pyproject.toml
